import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from "../components/Header/index";
import Footer from "../components/Footer/index";
import StoreProvider from "../providers/StoreProvider";
import React from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Custom Doors',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <Header/>
          <StoreProvider>
              {children}
          </StoreProvider>
          {/*<Footer/>*/}
      </body>
    </html>
  )
}
